---
- hosts: all
#  vars:
#    - ansible_connection: winrm
#    - ansible_port: 5986
#    - ansible_winrm_server_cert_validation: ignore
#    - ansible_winrm_transport: ntlm

  tasks:
    
  - name: "CReate directory strucuture"
    ansible.windows.win_file:
      path: C:\temp
      state: directory

  - name: "A single  ansible.txt text file is created"
    ansible.windows.win_copy:
      content: 'This is the Server Windows server managed by ansible'
      dest: C:\temp\ansible.txt


